from __future__ import annotations

import re
import sys
from datetime import date, datetime, time
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, field_validator

metamodel_version = "None"
version = "None"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="allow",
        coerce_numbers_to_str=True,
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "https://echemdb.github.io/metadata-schema/svgdigitizer_package/",
        "default_range": "string",
        "description": "Data package schema for svgdigitizer output.",
        "id": "https://echemdb.github.io/metadata-schema/svgdigitizer_package",
        "imports": ["linkml:types", "./figure_description", "./general/url"],
        "name": "svgdigitizer_package",
        "prefixes": {
            "echemdb": {
                "prefix_prefix": "echemdb",
                "prefix_reference": "https://echemdb.github.io/metadata-schema/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "D:\\github\\echemdb\\metadata-schema\\linkml\\svgdigitizer_package.yaml",
    }
)


class UncertaintyType(str, Enum):
    """
    Type of uncertainty measurement.
    """

    absolute = "absolute"
    """
    Absolute uncertainty value.
    """
    relative = "relative"
    """
    Relative uncertainty value.
    """


class FigureDescriptionType(str, Enum):
    """
    Source or origin of the data.
    """

    digitized = "digitized"
    """
    Data extracted from a figure using software (e.g., svgdigitizer).
    """
    raw = "raw"
    """
    Original data as recorded by the instrument.
    """
    simulated = "simulated"
    """
    Data generated by simulation software.
    """
    processed = "processed"
    """
    Data generated by processing raw or simulated data.
    """


class FieldOrientation(str, Enum):
    """
    Axis orientation in plots.
    """

    horizontal = "horizontal"
    """
    Displayed on x-axis.
    """
    vertical = "vertical"
    """
    Displayed on y-axis.
    """


class Quantity(ConfiguredBaseModel):
    """
    A physical quantity with a value, unit, and optional uncertainty.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/general/quantity"}
    )

    value: Optional[str] = Field(
        default=None,
        description="""Numerical value (can be a number, string, or null).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "value",
                "domain_of": ["Quantity", "Uncertainty"],
                "examples": [{"value": "0.5"}],
            }
        },
    )
    unit: Optional[str] = Field(
        default=None,
        description="""Unit of measurement as a string (e.g., 'mol / l', 'V', 'mA / cm2'). Can also be an integer (e.g., 1 for dimensionless).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "unit",
                "domain_of": ["Quantity", "Uncertainty", "DataField"],
                "examples": [{"value": "mol / l"}],
            }
        },
    )
    uncertainty: Optional[Uncertainty] = Field(
        default=None,
        description="""Uncertainty information for a measured quantity.""",
        json_schema_extra={
            "linkml_meta": {"alias": "uncertainty", "domain_of": ["Quantity"]}
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes about the measurement or quantity.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": ["Quantity", "Uncertainty", "FigureDescription"],
                "examples": [{"value": "Measured at room temperature"}],
            }
        },
    )
    calculation: Optional[str] = Field(
        default=None,
        description="""Method or formula used to calculate this quantity.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "calculation",
                "domain_of": ["Quantity"],
                "examples": [{"value": "Obtained by multiplying U and I"}],
            }
        },
    )


class Uncertainty(ConfiguredBaseModel):
    """
    Uncertainty information for a measured quantity.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/general/quantity"}
    )

    value: Optional[float] = Field(
        default=None,
        description="""Symmetric uncertainty value (±).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "value",
                "domain_of": ["Quantity", "Uncertainty"],
                "examples": [{"value": "0.01"}],
            }
        },
    )
    unit: Optional[str] = Field(
        default=None,
        description="""Unit of the uncertainty value.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "unit",
                "domain_of": ["Quantity", "Uncertainty", "DataField"],
                "examples": [{"value": "mol / l"}],
            }
        },
    )
    positiveValue: Optional[float] = Field(
        default=None,
        description="""Upper bound (+) for asymmetric uncertainties.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "positiveValue",
                "domain_of": ["Uncertainty"],
                "examples": [{"value": "0.02"}],
            }
        },
    )
    negativeValue: Optional[float] = Field(
        default=None,
        description="""Lower bound (-) for asymmetric uncertainties.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "negativeValue",
                "domain_of": ["Uncertainty"],
                "examples": [{"value": "0.01"}],
            }
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional information about the uncertainty estimation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": ["Quantity", "Uncertainty", "FigureDescription"],
                "examples": [
                    {"value": "Standard deviation from 3 replicate measurements"}
                ],
            }
        },
    )
    type: Optional[UncertaintyType] = Field(
        default=None,
        description="""Type of uncertainty (absolute or relative).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": ["Uncertainty", "FigureDescription", "DataField"],
            }
        },
    )


class FigureDescription(ConfiguredBaseModel):
    """
    Description of the data to a figure or plot including data type and measurement details.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/figure_description"}
    )

    type: FigureDescriptionType = Field(
        default=...,
        description="""Source or origin of the data, such as digitized, raw, simulated, or processed.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": ["Uncertainty", "FigureDescription", "DataField"],
                "examples": [{"value": "raw"}],
            }
        },
    )
    measurementType: Optional[str] = Field(
        default=None,
        description="""Acronym type for the measurement performed, such as CV, EIS, XPS, etc.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "measurementType",
                "domain_of": ["FigureDescription"],
                "examples": [{"value": "CV"}],
            }
        },
    )
    simultaneousMeasurements: Optional[list[str]] = Field(
        default=None,
        description="""Other measurements performed simultaneously, such as ring current, IR, Raman, ICP-MS.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "simultaneousMeasurements",
                "domain_of": ["FigureDescription"],
            }
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes about the figure or data.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": ["Quantity", "Uncertainty", "FigureDescription"],
                "examples": [{"value": "Data below 0 V was cut off by the x-axis."}],
            }
        },
    )
    fields: Optional[list[DataField]] = Field(
        default=None,
        description="""Description of data fields/columns in the figure.""",
        json_schema_extra={
            "linkml_meta": {"alias": "fields", "domain_of": ["FigureDescription"]}
        },
    )
    scanRate: Optional[Quantity] = Field(
        default=None,
        description="""The rate at which the data has been recorded.""",
        json_schema_extra={
            "linkml_meta": {"alias": "scanRate", "domain_of": ["FigureDescription"]}
        },
    )


class DataField(ConfiguredBaseModel):
    """
    Description of a data field (column) compatible with frictionless table-schema and extended with echemdb-specific properties for physical quantities.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/figure_description"}
    )

    name: str = Field(
        default=...,
        description="""Name of the data field. Use single letters for specific systems. Otherwise use descriptive names like 't_rel', 'E_WE', or 'j_WE'.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": ["DataField"],
                "examples": [{"value": "E_WE"}],
            }
        },
    )
    type: Optional[str] = Field(
        default=None,
        description="""Data type of the field (string, number, integer, boolean, object, array, date, time, datetime, year, duration, geopoint, geojson, any).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": ["Uncertainty", "FigureDescription", "DataField"],
                "examples": [{"value": "number"}],
            }
        },
    )
    format: Optional[str] = Field(
        default=None,
        description="""Format specification for the field type (default, email, uri, binary, uuid for strings; default for numbers).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "format",
                "domain_of": ["DataField"],
                "examples": [{"value": "default"}],
            }
        },
    )
    title: Optional[str] = Field(
        default=None,
        description="""A human-readable title for this field.""",
        json_schema_extra={
            "linkml_meta": {"alias": "title", "domain_of": ["DataField"]}
        },
    )
    description: Optional[str] = Field(
        default=None,
        description="""A description of that field.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": ["DataField"],
                "examples": [
                    {
                        "value": "The potential measured between the working electrode "
                        "and reference electrode."
                    }
                ],
            }
        },
    )
    dimension: Optional[str] = Field(
        default=None,
        description="""Physical dimension of the field (e.g., 'time', 'potential', 'current density').""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "dimension",
                "domain_of": ["DataField"],
                "examples": [{"value": "potential"}],
            }
        },
    )
    unit: Optional[str] = Field(
        default=None,
        description="""Unit of measurement for this field (SI or conventional electrochemical units), following astropy's string unit notation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "unit",
                "domain_of": ["Quantity", "Uncertainty", "DataField"],
                "examples": [{"value": "V"}],
            }
        },
    )
    reference: Optional[str] = Field(
        default=None,
        description="""Reference electrode or reference point for this measurement (electrochemistry-specific).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "reference",
                "domain_of": ["DataField"],
                "examples": [{"value": "RHE"}],
            }
        },
    )
    orientation: Optional[FieldOrientation] = Field(
        default=None,
        description="""Axis orientation in plots (horizontal for x-axis, vertical for y-axis).""",
        json_schema_extra={
            "linkml_meta": {"alias": "orientation", "domain_of": ["DataField"]}
        },
    )


class SvgdigitizerPackage(ConfiguredBaseModel):
    """
    Data package schema for svgdigitizer output following the Frictionless Data Package specification with simplified echemdb metadata.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/svgdigitizer_package",
            "tree_root": True,
        }
    )

    resources: Optional[list[SvgdigitizerResource]] = Field(
        default=None,
        description="""Data resources within the package.""",
        json_schema_extra={
            "linkml_meta": {"alias": "resources", "domain_of": ["SvgdigitizerPackage"]}
        },
    )


class SvgdigitizerResource(ConfiguredBaseModel):
    """
    A resource created by svgdigitizer with minimal echemdb metadata.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/svgdigitizer_package"
        }
    )

    metadata: Optional[SvgdigitizerResourceMetadata] = Field(
        default=None,
        description="""Metadata container for the digitized resource.""",
        json_schema_extra={
            "linkml_meta": {"alias": "metadata", "domain_of": ["SvgdigitizerResource"]}
        },
    )


class SvgdigitizerResourceMetadata(ConfiguredBaseModel):
    """
    Metadata container for svgdigitizer output.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/svgdigitizer_package"
        }
    )

    echemdb: SvgdigitizerEchemdbMetadata = Field(
        default=...,
        description="""Simplified echemdb metadata for digitized data.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "echemdb",
                "domain_of": ["SvgdigitizerResourceMetadata"],
            }
        },
    )


class SvgdigitizerEchemdbMetadata(ConfiguredBaseModel):
    """
    Simplified echemdb metadata for digitized data.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/svgdigitizer_package"
        }
    )

    experimental: Optional[SvgdigitizerExperimental] = Field(
        default=None,
        description="""Experimental tags or keywords.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "experimental",
                "domain_of": ["SvgdigitizerEchemdbMetadata"],
            }
        },
    )
    figureDescription: FigureDescription = Field(
        default=...,
        description="""Description of the digitized figure.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "figureDescription",
                "domain_of": ["SvgdigitizerEchemdbMetadata"],
            }
        },
    )
    source: Optional[SvgdigitizerSource] = Field(
        default=None,
        description="""Source publication information for digitized data.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "source",
                "domain_of": ["SvgdigitizerEchemdbMetadata"],
            }
        },
    )


class SvgdigitizerExperimental(ConfiguredBaseModel):
    """
    Experimental tags or keywords for svgdigitizer.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/svgdigitizer_package"
        }
    )

    tags: Optional[list[str]] = Field(
        default=None,
        description="""List of tags describing the experiment or measurement.""",
        json_schema_extra={
            "linkml_meta": {"alias": "tags", "domain_of": ["SvgdigitizerExperimental"]}
        },
    )


class SvgdigitizerSource(ConfiguredBaseModel):
    """
    Source publication information for digitized data.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/svgdigitizer_package"
        }
    )

    figure: Optional[str] = Field(
        default=None,
        description="""Figure identifier in the source publication.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "figure",
                "domain_of": ["SvgdigitizerSource"],
                "examples": [{"value": "2a"}],
            }
        },
    )
    curve: Optional[str] = Field(
        default=None,
        description="""Specific curve identifier within the figure.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "curve",
                "domain_of": ["SvgdigitizerSource"],
                "examples": [{"value": "blue"}],
            }
        },
    )
    citationKey: Optional[str] = Field(
        default=None,
        description="""BibTeX citation key for the source following <FirstAuthorName>_<Year>_<FirstWordOfTitle>_<FirstPageNumber> format.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "citationKey",
                "domain_of": ["SvgdigitizerSource"],
                "examples": [{"value": "doe_2024_electrochemistry_543"}],
            }
        },
    )
    url: Optional[str] = Field(
        default=None,
        description="""URL or DOI of the source publication.""",
        json_schema_extra={
            "linkml_meta": {"alias": "url", "domain_of": ["SvgdigitizerSource"]}
        },
    )
    techniques: Optional[list[str]] = Field(
        default=None,
        description="""Techniques used in the source data.""",
        json_schema_extra={
            "linkml_meta": {"alias": "techniques", "domain_of": ["SvgdigitizerSource"]}
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
Quantity.model_rebuild()
Uncertainty.model_rebuild()
FigureDescription.model_rebuild()
DataField.model_rebuild()
SvgdigitizerPackage.model_rebuild()
SvgdigitizerResource.model_rebuild()
SvgdigitizerResourceMetadata.model_rebuild()
SvgdigitizerEchemdbMetadata.model_rebuild()
SvgdigitizerExperimental.model_rebuild()
SvgdigitizerSource.model_rebuild()
