# ********************************************************************
#  This file is part of mdstools.
#
#        Copyright (C) 2026 Albert Engstfeld
#
#  mdstools is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  mdstools is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with mdstools. If not, see <https://www.gnu.org/licenses/>.
# ********************************************************************
from __future__ import annotations

import re
import sys
from datetime import date, datetime, time
from decimal import Decimal
from enum import Enum
from typing import Any, ClassVar, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, field_validator

metamodel_version = "None"
version = "None"


class ConfiguredBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_assignment=True,
        validate_default=True,
        extra="allow",
        coerce_numbers_to_str=True,
        arbitrary_types_allowed=True,
        use_enum_values=True,
        strict=False,
    )
    pass


class LinkMLMeta(RootModel):
    root: dict[str, Any] = {}
    model_config = ConfigDict(frozen=True)

    def __getattr__(self, key: str):
        return getattr(self.root, key)

    def __getitem__(self, key: str):
        return self.root[key]

    def __setitem__(self, key: str, value):
        self.root[key] = value

    def __contains__(self, key: str) -> bool:
        return key in self.root


linkml_meta = LinkMLMeta(
    {
        "default_prefix": "https://echemdb.github.io/metadata-schema/svgdigitizer/",
        "default_range": "string",
        "description": "Metadata schema for the input YAML file used by svgdigitizer.",
        "id": "https://echemdb.github.io/metadata-schema/svgdigitizer",
        "imports": [
            "linkml:types",
            "./curation",
            "./eln",
            "./experimental",
            "./figure_description",
            "./projects",
            "./source",
            "./system",
        ],
        "name": "svgdigitizer",
        "prefixes": {
            "echemdb": {
                "prefix_prefix": "echemdb",
                "prefix_reference": "https://echemdb.github.io/metadata-schema/",
            },
            "linkml": {
                "prefix_prefix": "linkml",
                "prefix_reference": "https://w3id.org/linkml/",
            },
        },
        "source_file": "D:\\github\\echemdb\\metadata-schema\\linkml\\svgdigitizer.yaml",
    }
)


class CurationRole(str, Enum):
    """
    Role of a person in the data curation process.
    """

    experimentalist = "experimentalist"
    """
    A person that recorded the (meta)data.
    """
    curator = "curator"
    """
    A person that created a (meta)dataset from literature data.
    """
    reviewer = "reviewer"
    """
    A person that verified the (meta)data (usually literature data).
    """
    supervisor = "supervisor"
    """
    A person that supervised the experimentalist.
    """


class UncertaintyType(str, Enum):
    """
    Type of uncertainty measurement.
    """

    absolute = "absolute"
    """
    Absolute uncertainty value.
    """
    relative = "relative"
    """
    Relative uncertainty value.
    """


class FigureDescriptionType(str, Enum):
    """
    Source or origin of the data.
    """

    digitized = "digitized"
    """
    Data extracted from a figure using software (e.g., svgdigitizer).
    """
    raw = "raw"
    """
    Original data as recorded by the instrument.
    """
    simulated = "simulated"
    """
    Data generated by simulation software.
    """
    processed = "processed"
    """
    Data generated by processing raw or simulated data.
    """


class FieldOrientation(str, Enum):
    """
    Axis orientation in plots.
    """

    horizontal = "horizontal"
    """
    Displayed on x-axis.
    """
    vertical = "vertical"
    """
    Displayed on y-axis.
    """


class ElectrodeFunction(str, Enum):
    """
    Role of the electrode in the electrochemical cell.
    """

    working_electrode = "working electrode"
    """
    Electrode where the reaction of interest occurs.
    """
    counter_electrode = "counter electrode"
    """
    Electrode that completes the circuit.
    """
    reference_electrode = "reference electrode"
    """
    Electrode providing a stable reference potential.
    """


class ComponentType(str, Enum):
    """
    Role or function of the component in the electrolyte.
    """

    solvent = "solvent"
    """
    The solvent.
    """
    salt = "salt"
    """
    A salt added the solvent.
    """
    acid = "acid"
    """
    An acid added to the solvent.
    """
    base = "base"
    """
    A base added to the solvent.
    """
    gas = "gas"
    """
    A gas passed through the solvent.
    """
    solute = "solute"
    """
    A solute added to the solvent, which is not a salt, acid, base or a gas, i.e., water.
    """


class ElectrolyteType(str, Enum):
    """
    Type of electrolyte defined by the solvent.
    """

    aqueous = "aqueous"
    """
    The solvent is water.
    """
    ionic_liquid = "ionic liquid"
    """
    The solvent is an ionic liquid.
    """
    non_aqueous = "non-aqueous"
    """
    The solvent is non-aqueous other than an ionic liquid, i.e., an organic compound.
    """
    solid = "solid"
    """
    A solid electrolyte.
    """


class SystemType(str, Enum):
    """
    Type of experimental system.
    """

    electrochemical = "electrochemical"
    """
    An electrochemical system consisting of electrodes, an electrolyte, and an electrochemical cell.
    """


class Curation(ConfiguredBaseModel):
    """
    Details on the curation process of the data.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/curation"}
    )

    process: list[Process] = Field(
        default=...,
        description="""List of people involved in creating, recording, or curating this data.""",
        json_schema_extra={
            "linkml_meta": {"alias": "process", "domain_of": ["Curation"]}
        },
    )


class Process(ConfiguredBaseModel):
    """
    A person involved in the data curation process.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/curation"}
    )

    role: CurationRole = Field(
        default=...,
        description="""Role of the person in the data curation process.""",
        json_schema_extra={"linkml_meta": {"alias": "role", "domain_of": ["Process"]}},
    )
    name: str = Field(
        default=...,
        description="""Full name of the person.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
                "examples": [{"value": "Jane Doe"}],
            }
        },
    )
    orcid: str = Field(
        default=...,
        description="""An URL containing the ORCID.""",
        json_schema_extra={"linkml_meta": {"alias": "orcid", "domain_of": ["Process"]}},
    )
    date: Optional[date] = Field(
        default=None,
        description="""Date when the person performed their role (ISO 8601 format: YYYY-MM-DD).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "date",
                "domain_of": ["Process"],
                "examples": [{"value": "2024-01-15"}],
            }
        },
    )


class Eln(ConfiguredBaseModel):
    """
    Electronic lab notebook (ELN) reference for the experiment.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/eln"}
    )

    url: str = Field(
        default=...,
        description="""URL to the electronic lab notebook entry.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )


class Instrumentation(ConfiguredBaseModel):
    """
    The instruments used to perform the experiment.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/experimental/instrumentation"
        }
    )

    type: Optional[str] = Field(
        default=None,
        description="""Type or category of instrument.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "potentiostat"}],
            }
        },
    )
    manufacturer: Optional[str] = Field(
        default=None,
        description="""Manufacturer of the instrument.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "manufacturer",
                "domain_of": ["Instrumentation", "ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "Awesome Supplier Inc."}],
            }
        },
    )
    name: str = Field(
        default=...,
        description="""Name or identifier of the instrument.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
                "examples": [{"value": "Poti05"}],
            }
        },
    )
    model: Optional[str] = Field(
        default=None,
        description="""Model number or designation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "model",
                "domain_of": ["Instrumentation", "ElectrodeSource"],
                "examples": [{"value": "P302NX5"}],
            }
        },
    )
    supplier: Optional[str] = Field(
        default=None,
        description="""Supplier of the instrument.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "supplier",
                "domain_of": ["Instrumentation", "ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "Awesome Supplier Inc."}],
            }
        },
    )


class Experimental(ConfiguredBaseModel):
    """
    Details about the configuration of the experimental setup.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/experimental"}
    )

    tags: Optional[list[str]] = Field(
        default=None,
        description="""Keywords or tags describing the experiment, such as BCV, ORR, COOR, XPS, or MS.""",
        json_schema_extra={
            "linkml_meta": {"alias": "tags", "domain_of": ["Experimental"]}
        },
    )
    url: Optional[str] = Field(
        default=None,
        description="""URL to related documentation, publication (DOI), or ELN entry.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )
    instrumentation: Optional[list[Instrumentation]] = Field(
        default=None,
        description="""Instruments and equipment used in the experiment.""",
        json_schema_extra={
            "linkml_meta": {"alias": "instrumentation", "domain_of": ["Experimental"]}
        },
    )
    description: Optional[str] = Field(
        default=None,
        description="""Detailed description of the experimental setup and conditions.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {
                        "value": "Cyclic voltammetry performed at room temperature with "
                        "50 mV/s scan rate"
                    }
                ],
            }
        },
    )


class Quantity(ConfiguredBaseModel):
    """
    A physical quantity with a value, unit, and optional uncertainty.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/general/quantity"}
    )

    value: Optional[float] = Field(
        default=None,
        description="""Numerical value of the quantity.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "value",
                "domain_of": ["Quantity", "Uncertainty", "Purity"],
                "examples": [{"value": "0.5"}],
            }
        },
    )
    unit: Optional[str] = Field(
        default=None,
        description="""Unit of measurement following astropy's string notation (e.g., 'mol / l', 'V', 'mA / cm2'). Use an empty string for dimensionless quantities.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "unit",
                "domain_of": ["Quantity", "Uncertainty", "DataField", "Purity"],
                "examples": [{"value": "mol / l"}],
            }
        },
    )
    uncertainty: Optional[Uncertainty] = Field(
        default=None,
        description="""Uncertainty information for a measured quantity.""",
        json_schema_extra={
            "linkml_meta": {"alias": "uncertainty", "domain_of": ["Quantity"]}
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes about the measurement or quantity.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
                "examples": [{"value": "Measured at room temperature"}],
            }
        },
    )
    calculation: Optional[str] = Field(
        default=None,
        description="""Method or formula used to calculate this quantity.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "calculation",
                "domain_of": ["Quantity"],
                "examples": [{"value": "Obtained by multiplying U and I"}],
            }
        },
    )


class Uncertainty(ConfiguredBaseModel):
    """
    Uncertainty information for a measured quantity.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/general/quantity"}
    )

    value: Optional[float] = Field(
        default=None,
        description="""Symmetric uncertainty value (±).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "value",
                "domain_of": ["Quantity", "Uncertainty", "Purity"],
                "examples": [{"value": "0.01"}],
            }
        },
    )
    unit: Optional[str] = Field(
        default=None,
        description="""Unit of the uncertainty value, following astropy's string notation. Use an empty string for dimensionless quantities.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "unit",
                "domain_of": ["Quantity", "Uncertainty", "DataField", "Purity"],
                "examples": [{"value": "mol / l"}],
            }
        },
    )
    positiveValue: Optional[float] = Field(
        default=None,
        description="""Upper bound (+) for asymmetric uncertainties.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "positiveValue",
                "domain_of": ["Uncertainty"],
                "examples": [{"value": "0.02"}],
            }
        },
    )
    negativeValue: Optional[float] = Field(
        default=None,
        description="""Lower bound (-) for asymmetric uncertainties.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "negativeValue",
                "domain_of": ["Uncertainty"],
                "examples": [{"value": "0.01"}],
            }
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional information about the uncertainty estimation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {"value": "Standard deviation from 3 replicate measurements"}
                ],
            }
        },
    )
    type: Optional[UncertaintyType] = Field(
        default=None,
        description="""Type of uncertainty (absolute or relative).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
            }
        },
    )


class FigureDescription(ConfiguredBaseModel):
    """
    Description of the data to a figure or plot including data type and measurement details.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/figure_description"}
    )

    type: FigureDescriptionType = Field(
        default=...,
        description="""Source or origin of the data, such as digitized, raw, simulated, or processed.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "raw"}],
            }
        },
    )
    measurementType: Optional[str] = Field(
        default=None,
        description="""Acronym type for the measurement performed, such as CV, EIS, XPS, etc.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "measurementType",
                "domain_of": ["FigureDescription"],
                "examples": [{"value": "CV"}],
            }
        },
    )
    simultaneousMeasurements: Optional[list[str]] = Field(
        default=None,
        description="""Other measurements performed simultaneously, such as ring current, IR, Raman, ICP-MS.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "simultaneousMeasurements",
                "domain_of": ["FigureDescription"],
            }
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes about the figure or data.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
                "examples": [{"value": "Data below 0 V was cut off by the x-axis."}],
            }
        },
    )
    fields: Optional[list[DataField]] = Field(
        default=None,
        description="""Description of data fields/columns in the figure.""",
        json_schema_extra={
            "linkml_meta": {"alias": "fields", "domain_of": ["FigureDescription"]}
        },
    )
    scanRate: Optional[Quantity] = Field(
        default=None,
        description="""The rate at which the data has been recorded.""",
        json_schema_extra={
            "linkml_meta": {"alias": "scanRate", "domain_of": ["FigureDescription"]}
        },
    )


class DataField(ConfiguredBaseModel):
    """
    Description of a data field (column) compatible with frictionless table-schema and extended with echemdb-specific properties for physical quantities.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/figure_description"}
    )

    name: str = Field(
        default=...,
        description="""Name of the data field. Use single letters for specific systems. Otherwise use descriptive names like 't_rel', 'E_WE', or 'j_WE'.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
                "examples": [{"value": "E_WE"}],
            }
        },
    )
    type: Optional[str] = Field(
        default=None,
        description="""Data type of the field (string, number, integer, boolean, object, array, date, time, datetime, year, duration, geopoint, geojson, any).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "number"}],
            }
        },
    )
    format: Optional[str] = Field(
        default=None,
        description="""Format specification for the field type (default, email, uri, binary, uuid for strings; default for numbers).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "format",
                "domain_of": ["DataField"],
                "examples": [{"value": "default"}],
            }
        },
    )
    title: Optional[str] = Field(
        default=None,
        description="""A human-readable title for this field.""",
        json_schema_extra={
            "linkml_meta": {"alias": "title", "domain_of": ["DataField", "Project"]}
        },
    )
    description: Optional[str] = Field(
        default=None,
        description="""A description of that field.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {
                        "value": "The potential measured between the working electrode "
                        "and reference electrode."
                    }
                ],
            }
        },
    )
    dimension: Optional[str] = Field(
        default=None,
        description="""Physical dimension of the field (e.g., 'time', 'potential', 'current density').""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "dimension",
                "domain_of": ["DataField"],
                "examples": [{"value": "potential"}],
            }
        },
    )
    unit: Optional[str] = Field(
        default=None,
        description="""Unit of measurement for this field (SI or conventional electrochemical units), following astropy's string unit notation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "unit",
                "domain_of": ["Quantity", "Uncertainty", "DataField", "Purity"],
                "examples": [{"value": "V"}],
            }
        },
    )
    reference: Optional[str] = Field(
        default=None,
        description="""Reference electrode or reference point for this measurement (electrochemistry-specific).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "reference",
                "domain_of": ["DataField"],
                "examples": [{"value": "RHE"}],
            }
        },
    )
    orientation: Optional[FieldOrientation] = Field(
        default=None,
        description="""Axis orientation in plots (horizontal for x-axis, vertical for y-axis).""",
        json_schema_extra={
            "linkml_meta": {"alias": "orientation", "domain_of": ["DataField"]}
        },
    )


class Project(ConfiguredBaseModel):
    """
    Information about a research project or funding source.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/projects"}
    )

    name: str = Field(
        default=...,
        description="""Short name or identifier of the project.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
                "examples": [{"value": "ERC-2024-STG"}],
            }
        },
    )
    title: Optional[str] = Field(
        default=None,
        description="""Full title of the project.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "title",
                "domain_of": ["DataField", "Project"],
                "examples": [
                    {
                        "value": "Understanding Electrocatalysis at the Molecular "
                        "Level"
                    }
                ],
            }
        },
    )
    type: Optional[str] = Field(
        default=None,
        description="""Type or category of project.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "ERC Starting Grant"}],
            }
        },
    )
    url: Optional[str] = Field(
        default=None,
        description="""URL to project website or information page.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )
    grantNumber: Optional[str] = Field(
        default=None,
        description="""Official grant or project number.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "grantNumber",
                "domain_of": ["Project"],
                "examples": [{"value": "123456"}],
            }
        },
    )


class Source(ConfiguredBaseModel):
    """
    Information about the source publication or dataset.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/source"}
    )

    citationKey: str = Field(
        default=...,
        description="""Unique citation key for bibliographic reference, usually <FirstAuthorName>_<Year>_<FirstWordOfTitle>_<FirstPageNumber>.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "citationKey",
                "domain_of": ["Source"],
                "examples": [{"value": "electrobear_2024_electrochemistry_563"}],
            }
        },
    )
    url: str = Field(
        default=...,
        description="""DOI (URL) to the publication or dataset.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )
    techniques: Optional[list[str]] = Field(
        default=None,
        description="""Experimental techniques used in the study.""",
        json_schema_extra={
            "linkml_meta": {"alias": "techniques", "domain_of": ["Source"]}
        },
    )
    figure: Optional[str] = Field(
        default=None,
        description="""Figure number or identifier from the source including subfigure label.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "figure",
                "domain_of": ["Source"],
                "examples": [{"value": "Figure 2a"}],
            }
        },
    )
    originalFilename: Optional[str] = Field(
        default=None,
        description="""Original filename of the data file.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "originalFilename",
                "domain_of": ["Source"],
                "examples": [{"value": "2023-04-24_cv_data_001.csv"}],
            }
        },
    )
    bibdata: Optional[str] = Field(
        default=None,
        description="""BibTeX bibliographic data.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "bibdata",
                "domain_of": ["Source"],
                "examples": [
                    {
                        "value": "@article{electrobear_2024_electrochemistry_563, "
                        "title={...}, ...}"
                    }
                ],
            }
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes about the source.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {"value": "The data in the figures of this work are blurry."}
                ],
            }
        },
    )
    curve: Optional[str] = Field(
        default=None,
        description="""Specific curve or trace identifier within a figure.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "curve",
                "domain_of": ["Source"],
                "examples": [{"value": "blue"}],
            }
        },
    )


class Purity(ConfiguredBaseModel):
    """
    Purity specifications of a chemical component.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/general/purity"}
    )

    grade: Optional[str] = Field(
        default=None,
        description="""Quality grade designation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "grade",
                "domain_of": ["Purity"],
                "examples": [{"value": "ACS reagent"}],
            }
        },
    )
    totalOrganicCarbon: Optional[Quantity] = Field(
        default=None,
        description="""Value for the total organic carbon content measurement.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "totalOrganicCarbon",
                "domain_of": ["Purity", "Atmosphere"],
            }
        },
    )
    totalIonConductivity: Optional[Quantity] = Field(
        default=None,
        description="""Value for the total ionic conductivity measurement.""",
        json_schema_extra={
            "linkml_meta": {"alias": "totalIonConductivity", "domain_of": ["Purity"]}
        },
    )
    value: Optional[float] = Field(
        default=None,
        description="""Purity value as a number.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "value",
                "domain_of": ["Quantity", "Uncertainty", "Purity"],
                "examples": [{"value": "99.9"}],
            }
        },
    )
    unit: Optional[str] = Field(
        default=None,
        description="""Unit for purity value.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "unit",
                "domain_of": ["Quantity", "Uncertainty", "DataField", "Purity"],
                "examples": [{"value": "pct"}],
            }
        },
    )
    container: Optional[str] = Field(
        default=None,
        description="""Name or identifier of the container in which the chemical is stored.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "container",
                "domain_of": ["Purity"],
                "examples": [{"value": "Glass bottle, amber"}],
            }
        },
    )
    internalLot: Optional[str] = Field(
        default=None,
        description="""Internal LOT or batch number.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "internalLot",
                "domain_of": ["Purity"],
                "examples": [{"value": "LOT-2024-001"}],
            }
        },
    )
    url: Optional[str] = Field(
        default=None,
        description="""URL with further details on the purity or container.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )
    refinement: Optional[str] = Field(
        default=None,
        description="""Description of additional purification or treatment performed.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "refinement",
                "domain_of": ["Purity", "ComponentSource"],
                "examples": [{"value": "Triple distilled"}],
            }
        },
    )


class Electrode(ConfiguredBaseModel):
    """
    An electrode used in the electrochemical cell, such as working, reference, counter, or collector electrode.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/electrode"}
    )

    name: str = Field(
        default=...,
        description="""Name or identifier for the electrode.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
                "examples": [{"value": "WE1"}],
            }
        },
    )
    function: str = Field(
        default=...,
        description="""Role of the electrode in the electrochemical cell. Typical values: working electrode, counter electrode, reference electrode.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "function",
                "domain_of": ["Electrode"],
                "examples": [{"value": "working electrode"}],
            }
        },
    )
    redoxSystem: Optional[str] = Field(
        default=None,
        description="""Name of the reference electrode redox system (RHE, SCE, Ag/AgCl, etc.).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "redoxSystem",
                "domain_of": ["Electrode"],
                "examples": [{"value": "RHE"}],
            }
        },
    )
    description: Optional[str] = Field(
        default=None,
        description="""Detailed description of the electrode (especially for custom-made electrodes).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {
                        "value": "Home-made Pt wire electrode, flame-annealed before "
                        "use"
                    }
                ],
            }
        },
    )
    geometricElectrolyteContactArea: Optional[Quantity] = Field(
        default=None,
        description="""Geometric surface area of electrode in contact with electrolyte.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "geometricElectrolyteContactArea",
                "domain_of": ["Electrode"],
            }
        },
    )
    purity: Optional[Purity] = Field(
        default=None,
        description="""Purity specifications of the electrode material.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "purity",
                "domain_of": [
                    "Electrode",
                    "ElectrodeSource",
                    "Component",
                    "ComponentSource",
                ],
            }
        },
    )
    preparationProcedure: Optional[ElectrodePreparation] = Field(
        default=None,
        description="""Procedures used to prepare the electrode before measurement.""",
        json_schema_extra={
            "linkml_meta": {"alias": "preparationProcedure", "domain_of": ["Electrode"]}
        },
    )
    shape: Optional[Shape] = Field(
        default=None,
        description="""Physical shape and dimensions of the electrode.""",
        json_schema_extra={
            "linkml_meta": {"alias": "shape", "domain_of": ["Electrode"]}
        },
    )
    source: Optional[ElectrodeSource] = Field(
        default=None,
        description="""Source and supplier information for the electrode.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "source",
                "domain_of": [
                    "Electrode",
                    "Component",
                    "ElectrochemicalCell",
                    "Svgdigitizer",
                ],
            }
        },
    )
    type: Optional[str] = Field(
        default=None,
        description="""Type of electrode, such as single crystal, powder catalyst, metal sheet, or metal wire.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "single crystal"}],
            }
        },
    )
    material: Optional[str] = Field(
        default=None,
        description="""Chemical symbol or abbreviation of the electrode material.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "material",
                "domain_of": ["Electrode"],
                "examples": [{"value": "Pt"}],
            }
        },
    )
    crystallographicOrientation: Optional[str] = Field(
        default=None,
        description="""Miller indices of the surface orientation or 'poly' for polycrystalline. Always use spaces for value separation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "crystallographicOrientation",
                "domain_of": ["Electrode"],
                "examples": [{"value": "(1 1 1)"}],
            }
        },
    )


class ElectrodeSource(ConfiguredBaseModel):
    """
    Information about the source and supplier of the electrode.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/electrode"}
    )

    manufacturer: Optional[str] = Field(
        default=None,
        description="""Name of the electrode manufacturer.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "manufacturer",
                "domain_of": ["Instrumentation", "ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "Your Favorite Crystals GmbH"}],
            }
        },
    )
    lot: Optional[str] = Field(
        default=None,
        description="""LOT or batch number.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "lot",
                "domain_of": ["ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "LOT-2024-PT111"}],
            }
        },
    )
    purity: Optional[Purity] = Field(
        default=None,
        description="""Purity specifications from the manufacturer or supplier.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "purity",
                "domain_of": [
                    "Electrode",
                    "ElectrodeSource",
                    "Component",
                    "ComponentSource",
                ],
            }
        },
    )
    model: Optional[str] = Field(
        default=None,
        description="""Model number or designation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "model",
                "domain_of": ["Instrumentation", "ElectrodeSource"],
                "examples": [{"value": "PT111-10"}],
            }
        },
    )
    url: Optional[str] = Field(
        default=None,
        description="""URL to product specification or datasheet.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )
    supplier: Optional[str] = Field(
        default=None,
        description="""Name of the supplier.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "supplier",
                "domain_of": ["Instrumentation", "ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "Chemicals & More Inc."}],
            }
        },
    )


class Shape(ConfiguredBaseModel):
    """
    Physical dimensions and shape of the electrode.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/electrode"}
    )

    type: Optional[str] = Field(
        default=None,
        description="""Type or shape of electrode.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "disc"}],
            }
        },
    )
    height: Optional[Quantity] = Field(
        default=None,
        description="""Height of the electrode.""",
        json_schema_extra={"linkml_meta": {"alias": "height", "domain_of": ["Shape"]}},
    )
    diameter: Optional[Quantity] = Field(
        default=None,
        description="""Diameter of the electrode (for cylindrical shapes).""",
        json_schema_extra={
            "linkml_meta": {"alias": "diameter", "domain_of": ["Shape"]}
        },
    )
    length: Optional[Quantity] = Field(
        default=None,
        description="""Length of the electrode.""",
        json_schema_extra={"linkml_meta": {"alias": "length", "domain_of": ["Shape"]}},
    )
    description: Optional[str] = Field(
        default=None,
        description="""Detailed description of the electrode shape.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
                "examples": [{"value": "Hemispherical tip"}],
            }
        },
    )


class ElectrodePreparation(ConfiguredBaseModel):
    """
    Procedures and methods used to prepare the electrode.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/electrode"}
    )

    url: Optional[str] = Field(
        default=None,
        description="""URL to detailed preparation protocol or procedure, such as an article DOI.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )
    description: Optional[list[str]] = Field(
        default=None,
        description="""Step-by-step description of preparation procedure.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
            }
        },
    )


class Component(ConfiguredBaseModel):
    """
    A chemical component of the electrolyte solution.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/general/component"}
    )

    name: str = Field(
        default=...,
        description="""Name or identifier of the chemical component (trivial name, formula, or IUPAC name).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
                "examples": [{"value": "H2SO4"}],
            }
        },
    )
    type: ComponentType = Field(
        default=...,
        description="""Role or function of the component in the electrolyte.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
            }
        },
    )
    chemicalIdentifiers: Optional[ChemicalIdentifiers] = Field(
        default=None,
        description="""Standard chemical identifiers (CAS, SMILES, InChI, etc.) for unambiguous identification.""",
        json_schema_extra={
            "linkml_meta": {"alias": "chemicalIdentifiers", "domain_of": ["Component"]}
        },
    )
    concentration: Optional[Quantity] = Field(
        default=None,
        description="""Concentration of the component in the electrolyte.""",
        json_schema_extra={
            "linkml_meta": {"alias": "concentration", "domain_of": ["Component"]}
        },
    )
    source: Optional[ComponentSource] = Field(
        default=None,
        description="""Information about the supplier and supplied quality of the chemical.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "source",
                "domain_of": [
                    "Electrode",
                    "Component",
                    "ElectrochemicalCell",
                    "Svgdigitizer",
                ],
            }
        },
    )
    purity: Optional[Purity] = Field(
        default=None,
        description="""Purity level of the chemical component after the purification process.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "purity",
                "domain_of": [
                    "Electrode",
                    "ElectrodeSource",
                    "Component",
                    "ComponentSource",
                ],
            }
        },
    )
    partialPressure: Optional[Quantity] = Field(
        default=None,
        description="""Partial pressure of a gaseous / volatile component.""",
        json_schema_extra={
            "linkml_meta": {"alias": "partialPressure", "domain_of": ["Component"]}
        },
    )
    proportion: Optional[Quantity] = Field(
        default=None,
        description="""Proportion of the component (e.g., volume percent, mole fraction).""",
        json_schema_extra={
            "linkml_meta": {"alias": "proportion", "domain_of": ["Component"]}
        },
    )
    flow: Optional[Quantity] = Field(
        default=None,
        description="""Flow rate for gaseous components.""",
        json_schema_extra={
            "linkml_meta": {"alias": "flow", "domain_of": ["Component"]}
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes or observations about this component.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
                "examples": [{"value": "Freshly prepared solution"}],
            }
        },
    )
    pressure: Optional[Quantity] = Field(
        default=None,
        description="""Pressure for gaseous components.""",
        json_schema_extra={
            "linkml_meta": {"alias": "pressure", "domain_of": ["Component"]}
        },
    )


class ComponentSource(ConfiguredBaseModel):
    """
    Information about the source and quality of the chemical component.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/general/component"}
    )

    supplier: Optional[str] = Field(
        default=None,
        description="""Name of the company that supplied the chemical.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "supplier",
                "domain_of": ["Instrumentation", "ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "Your Chemical Supplier Inc."}],
            }
        },
    )
    manufacturer: Optional[str] = Field(
        default=None,
        description="""Name of the company or organization that manufactured the chemical.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "manufacturer",
                "domain_of": ["Instrumentation", "ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "Organic Chemistry II - Bar Group"}],
            }
        },
    )
    lot: Optional[str] = Field(
        default=None,
        description="""LOT or batch number provided by the manufacturer or supplier for traceability.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "lot",
                "domain_of": ["ElectrodeSource", "ComponentSource"],
                "examples": [{"value": "LOT12345"}],
            }
        },
    )
    purity: Optional[Purity] = Field(
        default=None,
        description="""Stated purity level from the supplier or manufacturer.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "purity",
                "domain_of": [
                    "Electrode",
                    "ElectrodeSource",
                    "Component",
                    "ComponentSource",
                ],
            }
        },
    )
    refinement: Optional[str] = Field(
        default=None,
        description="""Any additional purification or treatment performed.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "refinement",
                "domain_of": ["Purity", "ComponentSource"],
                "examples": [{"value": "Recrystallized from ethanol"}],
            }
        },
    )
    quality: Optional[str] = Field(
        default=None,
        description="""Quality grade of the chemical.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "quality",
                "domain_of": ["ComponentSource"],
                "examples": [{"value": "ACS reagent grade"}],
            }
        },
    )


class Electrolyte(ConfiguredBaseModel):
    """
    The properties and components of the electrolyte solution.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/electrolyte"}
    )

    type: ElectrolyteType = Field(
        default=...,
        description="""Type of electrolyte defined by the solvent.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "aqueous"}],
            }
        },
    )
    electrolyteContainer: Optional[ElectrolyteContainer] = Field(
        default=None,
        description="""Container used to prepare or store the electrolyte before the measurement.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "electrolyteContainer",
                "domain_of": ["Electrolyte"],
            }
        },
    )
    components: Optional[list[Component]] = Field(
        default=None,
        description="""Chemical components of the electrolyte including solvents, salts, acids, bases, and gases.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "components",
                "domain_of": [
                    "Electrolyte",
                    "ElectrolyteContainer",
                    "ElectrochemicalCell",
                    "Atmosphere",
                ],
            }
        },
    )
    ph: Optional[Quantity] = Field(
        default=None,
        description="""pH value of the electrolyte solution.""",
        json_schema_extra={
            "linkml_meta": {"alias": "ph", "domain_of": ["Electrolyte"]}
        },
    )
    temperature: Optional[Quantity] = Field(
        default=None,
        description="""Temperature of the electrolyte during the experiment.""",
        json_schema_extra={
            "linkml_meta": {"alias": "temperature", "domain_of": ["Electrolyte"]}
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes or observations about the electrolyte.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {"value": "Electrolyte was not replaced between measurements."}
                ],
            }
        },
    )


class ElectrolyteContainer(ConfiguredBaseModel):
    """
    Container used to prepare or store the electrolyte before the measurement.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/electrolyte"}
    )

    description: Optional[str] = Field(
        default=None,
        description="""The vessel in which the supplying electrolyte was prepared or stored before the measurement.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
            }
        },
    )
    components: Optional[list[ElectrolyteContainerComponent]] = Field(
        default=None,
        description="""Components of the electrolyte container.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "components",
                "domain_of": [
                    "Electrolyte",
                    "ElectrolyteContainer",
                    "ElectrochemicalCell",
                    "Atmosphere",
                ],
            }
        },
    )


class ElectrolyteContainerComponent(ConfiguredBaseModel):
    """
    A component of the electrolyte container.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/electrolyte"}
    )

    name: Optional[str] = Field(
        default=None,
        description="""A unique identifier.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
            }
        },
    )
    type: Optional[str] = Field(
        default=None,
        description="""The type of the container, i.e., a flask.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
            }
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
            }
        },
    )


class ElectrochemicalCell(ConfiguredBaseModel):
    """
    Description of the electrochemical cell setup and configuration.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/system/electrochemical_cell"
        }
    )

    type: Optional[str] = Field(
        default=None,
        description="""Type of electrochemical cell, such as H-cell, beaker glass, flow cell.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "H-cell"}],
            }
        },
    )
    components: Optional[list[ElectrochemicalCellComponent]] = Field(
        default=None,
        description="""Physical components and parts of the cell that are in contact with the electrolyte.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "components",
                "domain_of": [
                    "Electrolyte",
                    "ElectrolyteContainer",
                    "ElectrochemicalCell",
                    "Atmosphere",
                ],
            }
        },
    )
    cellDescription: Optional[str] = Field(
        default=None,
        description="""Detailed description of the cell configuration.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "cellDescription",
                "domain_of": ["ElectrochemicalCell"],
                "examples": [
                    {"value": "Three-electrode setup with glass cell and Teflon " "cap"}
                ],
            }
        },
    )
    cleaningProcedure: Optional[str] = Field(
        default=None,
        description="""Procedure used to clean the cell before experiments.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "cleaningProcedure",
                "domain_of": ["ElectrochemicalCell"],
                "examples": [
                    {
                        "value": "Cleaned with aqua regia, rinsed with ultrapure water, "
                        "and dried in Ar stream"
                    }
                ],
            }
        },
    )
    source: Optional[ElectrochemicalCellSource] = Field(
        default=None,
        description="""Source and supplier information for the cell.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "source",
                "domain_of": [
                    "Electrode",
                    "Component",
                    "ElectrochemicalCell",
                    "Svgdigitizer",
                ],
            }
        },
    )


class ElectrochemicalCellComponent(ConfiguredBaseModel):
    """
    A component or part of the electrochemical cell.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/system/electrochemical_cell"
        }
    )

    name: str = Field(
        default=...,
        description="""Name or identifier of the component.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "name",
                "domain_of": [
                    "Process",
                    "Instrumentation",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Component",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCellComponent",
                ],
                "examples": [{"value": "Cell body"}],
            }
        },
    )
    part: str = Field(
        default=...,
        description="""Part number or designation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "part",
                "domain_of": ["ElectrochemicalCellComponent"],
                "examples": [{"value": "EC-CELL-100"}],
            }
        },
    )
    description: Optional[str] = Field(
        default=None,
        description="""Detailed description of the component.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
                "examples": [{"value": "Borosilicate glass cell with multiple ports"}],
            }
        },
    )


class ElectrochemicalCellSource(ConfiguredBaseModel):
    """
    Source information for the electrochemical cell.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/system/electrochemical_cell"
        }
    )

    url: Optional[str] = Field(
        default=None,
        description="""URL to product page or technical documentation.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )


class ChemicalIdentifiers(ConfiguredBaseModel):
    """
    Standard chemical identifiers for unambiguous identification of compounds.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/general/chemical_identifiers"
        }
    )

    cas: Optional[str] = Field(
        default=None,
        description="""CAS Registry Number (Chemical Abstracts Service identifier).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "cas",
                "domain_of": ["ChemicalIdentifiers"],
                "examples": [{"value": "7664-93-9"}],
            }
        },
    )
    inchi: Optional[str] = Field(
        default=None,
        description="""InChI (International Chemical Identifier) string.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "inchi",
                "domain_of": ["ChemicalIdentifiers"],
                "examples": [{"value": "InChI=1S/H2O4S/c1-5(2,3)4/h(H2,1,2,3,4)"}],
            }
        },
    )
    inchikey: Optional[str] = Field(
        default=None,
        description="""InChIKey (hashed InChI for easier searching).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "inchikey",
                "domain_of": ["ChemicalIdentifiers"],
                "examples": [{"value": "QAOWNCQODCNURD-UHFFFAOYSA-N"}],
            }
        },
    )


class Atmosphere(ConfiguredBaseModel):
    """
    Atmospheric conditions and gas composition during the experiment.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system/atmosphere"}
    )

    type: Optional[str] = Field(
        default=None,
        description="""Type of atmospheric condition, such as inert (Ar saturated), ambient, UHV (ultra high vacuum).""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "inert"}],
            }
        },
    )
    totalOrganicCarbon: Optional[Quantity] = Field(
        default=None,
        description="""Total organic carbon content measurement in the atmosphere.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "totalOrganicCarbon",
                "domain_of": ["Purity", "Atmosphere"],
            }
        },
    )
    components: Optional[list[Component]] = Field(
        default=None,
        description="""Gas components present in the atmosphere.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "components",
                "domain_of": [
                    "Electrolyte",
                    "ElectrolyteContainer",
                    "ElectrochemicalCell",
                    "Atmosphere",
                ],
            }
        },
    )
    url: Optional[str] = Field(
        default=None,
        description="""URL with further details on the atmospheric setup or control system.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "url",
                "domain_of": [
                    "Eln",
                    "Experimental",
                    "Project",
                    "Source",
                    "Purity",
                    "ElectrodeSource",
                    "ElectrodePreparation",
                    "ElectrochemicalCellSource",
                    "Atmosphere",
                ],
            }
        },
    )
    description: Optional[str] = Field(
        default=None,
        description="""Detailed description of the atmospheric conditions.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "description",
                "domain_of": [
                    "Experimental",
                    "DataField",
                    "Electrode",
                    "Shape",
                    "ElectrodePreparation",
                    "ElectrolyteContainer",
                    "ElectrochemicalCellComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {"value": "Argon purged for 30 minutes before measurement"}
                ],
            }
        },
    )
    comment: Optional[str] = Field(
        default=None,
        description="""Additional notes about the atmosphere.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "comment",
                "domain_of": [
                    "Quantity",
                    "Uncertainty",
                    "FigureDescription",
                    "Source",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "Atmosphere",
                ],
                "examples": [
                    {"value": "Slight overpressure maintained throughout " "experiment"}
                ],
            }
        },
    )


class System(ConfiguredBaseModel):
    """
    Description of the experimental system including electrodes, electrolyte, and environmental conditions.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {"from_schema": "https://echemdb.github.io/metadata-schema/system"}
    )

    type: SystemType = Field(
        default=...,
        description="""Type of experimental system.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "type",
                "domain_of": [
                    "Instrumentation",
                    "Uncertainty",
                    "FigureDescription",
                    "DataField",
                    "Project",
                    "Electrode",
                    "Shape",
                    "Component",
                    "Electrolyte",
                    "ElectrolyteContainerComponent",
                    "ElectrochemicalCell",
                    "Atmosphere",
                    "System",
                ],
                "examples": [{"value": "electrochemical"}],
            }
        },
    )
    electrolyte: Electrolyte = Field(
        default=...,
        description="""The electrolyte solution used in the experiment.""",
        json_schema_extra={
            "linkml_meta": {"alias": "electrolyte", "domain_of": ["System"]}
        },
    )
    electrodes: list[Electrode] = Field(
        default=...,
        description="""List of electrodes used in the electrochemical cell (working, reference, counter electrodes, ring electrodes).""",
        json_schema_extra={
            "linkml_meta": {"alias": "electrodes", "domain_of": ["System"]}
        },
    )
    electrochemicalCell: Optional[ElectrochemicalCell] = Field(
        default=None,
        description="""Description of the electrochemical cell and its configuration.""",
        json_schema_extra={
            "linkml_meta": {"alias": "electrochemicalCell", "domain_of": ["System"]}
        },
    )
    atmosphere: Optional[Atmosphere] = Field(
        default=None,
        description="""Atmospheric conditions during the experiment.""",
        json_schema_extra={
            "linkml_meta": {"alias": "atmosphere", "domain_of": ["System"]}
        },
    )


class Svgdigitizer(ConfiguredBaseModel):
    """
    Metadata schema for the input YAML file used by svgdigitizer to create echemdb compatible data packages.
    """

    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta(
        {
            "from_schema": "https://echemdb.github.io/metadata-schema/svgdigitizer",
            "tree_root": True,
        }
    )

    curation: Curation = Field(
        default=...,
        description="""Details on the curation process of the data.""",
        json_schema_extra={
            "linkml_meta": {"alias": "curation", "domain_of": ["Svgdigitizer"]}
        },
    )
    eln: Optional[Eln] = Field(
        default=None,
        description="""Electronic lab notebook reference.""",
        json_schema_extra={
            "linkml_meta": {"alias": "eln", "domain_of": ["Svgdigitizer"]}
        },
    )
    experimental: Optional[Experimental] = Field(
        default=None,
        description="""Details about the experimental setup.""",
        json_schema_extra={
            "linkml_meta": {"alias": "experimental", "domain_of": ["Svgdigitizer"]}
        },
    )
    figureDescription: Optional[FigureDescription] = Field(
        default=None,
        description="""Description of the data to a figure or plot.""",
        json_schema_extra={
            "linkml_meta": {"alias": "figureDescription", "domain_of": ["Svgdigitizer"]}
        },
    )
    projects: Optional[list[Project]] = Field(
        default=None,
        description="""Research projects or funding sources.""",
        json_schema_extra={
            "linkml_meta": {"alias": "projects", "domain_of": ["Svgdigitizer"]}
        },
    )
    source: Source = Field(
        default=...,
        description="""Information about the source publication or dataset.""",
        json_schema_extra={
            "linkml_meta": {
                "alias": "source",
                "domain_of": [
                    "Electrode",
                    "Component",
                    "ElectrochemicalCell",
                    "Svgdigitizer",
                ],
            }
        },
    )
    system: System = Field(
        default=...,
        description="""Description of the experimental system.""",
        json_schema_extra={
            "linkml_meta": {"alias": "system", "domain_of": ["Svgdigitizer"]}
        },
    )


# Model rebuild
# see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
Curation.model_rebuild()
Process.model_rebuild()
Eln.model_rebuild()
Instrumentation.model_rebuild()
Experimental.model_rebuild()
Quantity.model_rebuild()
Uncertainty.model_rebuild()
FigureDescription.model_rebuild()
DataField.model_rebuild()
Project.model_rebuild()
Source.model_rebuild()
Purity.model_rebuild()
Electrode.model_rebuild()
ElectrodeSource.model_rebuild()
Shape.model_rebuild()
ElectrodePreparation.model_rebuild()
Component.model_rebuild()
ComponentSource.model_rebuild()
Electrolyte.model_rebuild()
ElectrolyteContainer.model_rebuild()
ElectrolyteContainerComponent.model_rebuild()
ElectrochemicalCell.model_rebuild()
ElectrochemicalCellComponent.model_rebuild()
ElectrochemicalCellSource.model_rebuild()
ChemicalIdentifiers.model_rebuild()
Atmosphere.model_rebuild()
System.model_rebuild()
Svgdigitizer.model_rebuild()
